name: bzl-playground

options:
  developmentLanguage: en
  useBaseInternationalization: false
  deploymentTarget:
    iOS: "15.0"
  groupSortPosition: top
  generateEmptyDirectories: true
  createIntermediateGroups: true
  xcodeVersion: '14.0'

configs:
  Debug: debug
  Release: release

configFiles:
  Debug: xcconfigs/Debug.xcconfig
  Release: xcconfigs/Release.xcconfig


targets:
  bzl-playground:
    platform: iOS
    type: application

    sources:
      - path: bzl-playground

    configFiles:
      Debug: xcconfigs/bzl-playground-Debug.xcconfig
      Release: xcconfigs/bzl-playground-Release.xcconfig

  Tests:
    platform: iOS
    type: bundle.unit-test

    sources:
      - bzl-playgroundTests

    dependencies:
      - target: bzl-playground

    configFiles:
      Debug: xcconfigs/bzl-playgroundTests.xcconfig
      Release: xcconfigs/bzl-playgroundTests.xcconfig


schemes:
  bzl-playground:
    build:
      targets:
        bzl-playground: all
        Tests: [test]
    test:
      gatherCoverageData: true
      targets:
        - Tests